# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.23.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/apxf/Desktop/gits/mcl-xfap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/apxf/Desktop/gits/mcl-xfap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apxf/Desktop/gits/mcl-xfap/CMakeFiles /Users/apxf/Desktop/gits/mcl-xfap//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apxf/Desktop/gits/mcl-xfap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mcl

# Build rule for target.
mcl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcl
.PHONY : mcl

# fast build rule for target.
mcl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/build
.PHONY : mcl/fast

#=============================================================================
# Target rules for targets named mcl_st

# Build rule for target.
mcl_st: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcl_st
.PHONY : mcl_st

# fast build rule for target.
mcl_st/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/build
.PHONY : mcl_st/fast

#=============================================================================
# Target rules for targets named gen_bint.o

# Build rule for target.
gen_bint.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_bint.o
.PHONY : gen_bint.o

# fast build rule for target.
gen_bint.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_bint.o.dir/build.make CMakeFiles/gen_bint.o.dir/build
.PHONY : gen_bint.o/fast

#=============================================================================
# Target rules for targets named gen_base.o

# Build rule for target.
gen_base.o: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_base.o
.PHONY : gen_base.o

# fast build rule for target.
gen_base.o/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_base.o.dir/build.make CMakeFiles/gen_base.o.dir/build
.PHONY : gen_base.o/fast

#=============================================================================
# Target rules for targets named mclbn256

# Build rule for target.
mclbn256: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mclbn256
.PHONY : mclbn256

# fast build rule for target.
mclbn256/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/build
.PHONY : mclbn256/fast

#=============================================================================
# Target rules for targets named mclbn384

# Build rule for target.
mclbn384: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mclbn384
.PHONY : mclbn384

# fast build rule for target.
mclbn384/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/build
.PHONY : mclbn384/fast

#=============================================================================
# Target rules for targets named mclbn384_256

# Build rule for target.
mclbn384_256: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mclbn384_256
.PHONY : mclbn384_256

# fast build rule for target.
mclbn384_256/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/build
.PHONY : mclbn384_256/fast

#=============================================================================
# Target rules for targets named fp_test

# Build rule for target.
fp_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fp_test
.PHONY : fp_test

# fast build rule for target.
fp_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/fp_test.dir/build.make test/CMakeFiles/fp_test.dir/build
.PHONY : fp_test/fast

#=============================================================================
# Target rules for targets named ec_test

# Build rule for target.
ec_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ec_test
.PHONY : ec_test

# fast build rule for target.
ec_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ec_test.dir/build.make test/CMakeFiles/ec_test.dir/build
.PHONY : ec_test/fast

#=============================================================================
# Target rules for targets named fp_util_test

# Build rule for target.
fp_util_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fp_util_test
.PHONY : fp_util_test

# fast build rule for target.
fp_util_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/fp_util_test.dir/build.make test/CMakeFiles/fp_util_test.dir/build
.PHONY : fp_util_test/fast

#=============================================================================
# Target rules for targets named window_method_test

# Build rule for target.
window_method_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 window_method_test
.PHONY : window_method_test

# fast build rule for target.
window_method_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/window_method_test.dir/build.make test/CMakeFiles/window_method_test.dir/build
.PHONY : window_method_test/fast

#=============================================================================
# Target rules for targets named elgamal_test

# Build rule for target.
elgamal_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elgamal_test
.PHONY : elgamal_test

# fast build rule for target.
elgamal_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/elgamal_test.dir/build.make test/CMakeFiles/elgamal_test.dir/build
.PHONY : elgamal_test/fast

#=============================================================================
# Target rules for targets named bls12_test

# Build rule for target.
bls12_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bls12_test
.PHONY : bls12_test

# fast build rule for target.
bls12_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/bls12_test.dir/build.make test/CMakeFiles/bls12_test.dir/build
.PHONY : bls12_test/fast

#=============================================================================
# Target rules for targets named fp_tower_test

# Build rule for target.
fp_tower_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fp_tower_test
.PHONY : fp_tower_test

# fast build rule for target.
fp_tower_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/fp_tower_test.dir/build.make test/CMakeFiles/fp_tower_test.dir/build
.PHONY : fp_tower_test/fast

#=============================================================================
# Target rules for targets named gmp_test

# Build rule for target.
gmp_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmp_test
.PHONY : gmp_test

# fast build rule for target.
gmp_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/gmp_test.dir/build.make test/CMakeFiles/gmp_test.dir/build
.PHONY : gmp_test/fast

#=============================================================================
# Target rules for targets named bn_test

# Build rule for target.
bn_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_test
.PHONY : bn_test

# fast build rule for target.
bn_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/bn_test.dir/build.make test/CMakeFiles/bn_test.dir/build
.PHONY : bn_test/fast

#=============================================================================
# Target rules for targets named glv_test

# Build rule for target.
glv_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glv_test
.PHONY : glv_test

# fast build rule for target.
glv_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/glv_test.dir/build.make test/CMakeFiles/glv_test.dir/build
.PHONY : glv_test/fast

#=============================================================================
# Target rules for targets named static_init_test

# Build rule for target.
static_init_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 static_init_test
.PHONY : static_init_test

# fast build rule for target.
static_init_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/static_init_test.dir/build.make test/CMakeFiles/static_init_test.dir/build
.PHONY : static_init_test/fast

#=============================================================================
# Target rules for targets named bn_c256_test

# Build rule for target.
bn_c256_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_c256_test
.PHONY : bn_c256_test

# fast build rule for target.
bn_c256_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/bn_c256_test.dir/build.make test/CMakeFiles/bn_c256_test.dir/build
.PHONY : bn_c256_test/fast

#=============================================================================
# Target rules for targets named bn_c384_test

# Build rule for target.
bn_c384_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_c384_test
.PHONY : bn_c384_test

# fast build rule for target.
bn_c384_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/bn_c384_test.dir/build.make test/CMakeFiles/bn_c384_test.dir/build
.PHONY : bn_c384_test/fast

#=============================================================================
# Target rules for targets named bn_c384_256_test

# Build rule for target.
bn_c384_256_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_c384_256_test
.PHONY : bn_c384_256_test

# fast build rule for target.
bn_c384_256_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/bn_c384_256_test.dir/build.make test/CMakeFiles/bn_c384_256_test.dir/build
.PHONY : bn_c384_256_test/fast

#=============================================================================
# Target rules for targets named bint_test

# Build rule for target.
bint_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bint_test
.PHONY : bint_test

# fast build rule for target.
bint_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/bint_test.dir/build.make test/CMakeFiles/bint_test.dir/build
.PHONY : bint_test/fast

#=============================================================================
# Target rules for targets named vint_test

# Build rule for target.
vint_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vint_test
.PHONY : vint_test

# fast build rule for target.
vint_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/vint_test.dir/build.make test/CMakeFiles/vint_test.dir/build
.PHONY : vint_test/fast

src/bn_c256.o: src/bn_c256.cpp.o
.PHONY : src/bn_c256.o

# target to build an object file
src/bn_c256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/src/bn_c256.cpp.o
.PHONY : src/bn_c256.cpp.o

src/bn_c256.i: src/bn_c256.cpp.i
.PHONY : src/bn_c256.i

# target to preprocess a source file
src/bn_c256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/src/bn_c256.cpp.i
.PHONY : src/bn_c256.cpp.i

src/bn_c256.s: src/bn_c256.cpp.s
.PHONY : src/bn_c256.s

# target to generate assembly for a file
src/bn_c256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/src/bn_c256.cpp.s
.PHONY : src/bn_c256.cpp.s

src/bn_c384.o: src/bn_c384.cpp.o
.PHONY : src/bn_c384.o

# target to build an object file
src/bn_c384.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/src/bn_c384.cpp.o
.PHONY : src/bn_c384.cpp.o

src/bn_c384.i: src/bn_c384.cpp.i
.PHONY : src/bn_c384.i

# target to preprocess a source file
src/bn_c384.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/src/bn_c384.cpp.i
.PHONY : src/bn_c384.cpp.i

src/bn_c384.s: src/bn_c384.cpp.s
.PHONY : src/bn_c384.s

# target to generate assembly for a file
src/bn_c384.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/src/bn_c384.cpp.s
.PHONY : src/bn_c384.cpp.s

src/bn_c384_256.o: src/bn_c384_256.cpp.o
.PHONY : src/bn_c384_256.o

# target to build an object file
src/bn_c384_256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.o
.PHONY : src/bn_c384_256.cpp.o

src/bn_c384_256.i: src/bn_c384_256.cpp.i
.PHONY : src/bn_c384_256.i

# target to preprocess a source file
src/bn_c384_256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.i
.PHONY : src/bn_c384_256.cpp.i

src/bn_c384_256.s: src/bn_c384_256.cpp.s
.PHONY : src/bn_c384_256.s

# target to generate assembly for a file
src/bn_c384_256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.s
.PHONY : src/bn_c384_256.cpp.s

src/fp.o: src/fp.cpp.o
.PHONY : src/fp.o

# target to build an object file
src/fp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/fp.cpp.o
.PHONY : src/fp.cpp.o

src/fp.i: src/fp.cpp.i
.PHONY : src/fp.i

# target to preprocess a source file
src/fp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/fp.cpp.i
.PHONY : src/fp.cpp.i

src/fp.s: src/fp.cpp.s
.PHONY : src/fp.s

# target to generate assembly for a file
src/fp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/fp.cpp.s
.PHONY : src/fp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gen_base.o"
	@echo "... gen_bint.o"
	@echo "... bint_test"
	@echo "... bls12_test"
	@echo "... bn_c256_test"
	@echo "... bn_c384_256_test"
	@echo "... bn_c384_test"
	@echo "... bn_test"
	@echo "... ec_test"
	@echo "... elgamal_test"
	@echo "... fp_test"
	@echo "... fp_tower_test"
	@echo "... fp_util_test"
	@echo "... glv_test"
	@echo "... gmp_test"
	@echo "... mcl"
	@echo "... mcl_st"
	@echo "... mclbn256"
	@echo "... mclbn384"
	@echo "... mclbn384_256"
	@echo "... static_init_test"
	@echo "... vint_test"
	@echo "... window_method_test"
	@echo "... src/bn_c256.o"
	@echo "... src/bn_c256.i"
	@echo "... src/bn_c256.s"
	@echo "... src/bn_c384.o"
	@echo "... src/bn_c384.i"
	@echo "... src/bn_c384.s"
	@echo "... src/bn_c384_256.o"
	@echo "... src/bn_c384_256.i"
	@echo "... src/bn_c384_256.s"
	@echo "... src/fp.o"
	@echo "... src/fp.i"
	@echo "... src/fp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

